Controllers/CartController.cs
using Amazon_Replica.Services;
using Microsoft.AspNetCore.Mvc;

namespace Amazon_Replica.Controllers
{
    public class CartController : Controller
    {
        private readonly IProductRepo productRepo;
        private readonly ICartRepo cartRepo;

        public CartController(IProductRepo _productRepo, ICartRepo _cartRepo)
        {
            productRepo = _productRepo;
            cartRepo = _cartRepo;
        }

        public IActionResult Index()
        {
            var CartItems = cartRepo.GetCartItems();
            return View(CartItems);
        }

        public IActionResult AddToCart(int id)
        {
            cartRepo.AddToCart(id);

            return RedirectToAction("Index", "Store");
        }

        public IActionResult RemoveFromCart(string id)
        {
            var selectedProduct = cartRepo.GetCartItem(id);

            if (selectedProduct != null)
            {
                cartRepo.RemoveFromCart(id);
            }

            return RedirectToAction("Index");
        }

        public IActionResult ReduceQuantity(string id)
        {
            var selectedProduct = cartRepo.GetCartItem(id);

            if (selectedProduct != null)
            {
                cartRepo.ReduceQuantity(id);
            }

            return RedirectToAction("Index");
        }

        public IActionResult IncreaseQuantity(string id)
        {
            var selectedProduct = cartRepo.GetCartItem(id);

            if (selectedProduct != null)
            {
                cartRepo.IncreaseQuantity(id);
            }

            return RedirectToAction("Index");
        }

        public IActionResult ClearCart()
        {
            cartRepo.ClearCart();

            return RedirectToAction("Index");
        }
    }
}

Controllers/OrderController.cs
using Amazon_Replica.Areas.Identity.Data;
using Amazon_Replica.Models;
using Amazon_Replica.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Stripe;

namespace Amazon_Replica.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        UserManager<ApplicationUser> userManager;
        private readonly IOrderRepo orderRepo;
        private readonly ICartRepo cartRepo;

        public OrderController(IOrderRepo _orderRepo, ICartRepo cart, UserManager<ApplicationUser> _UserManager)
        {
            orderRepo = _orderRepo;
            cartRepo = cart;
            userManager = _UserManager;
        }

        [Authorize(Roles = "Admin,Moderator")]
        public async Task<IActionResult> Index()
        {
            return View(orderRepo.GetAll());
        }

        public IActionResult CheckOut()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CheckOut(Order order)
        {

            var cartItems = cartRepo.GetCartItems();
      
            var user = await userManager.FindByNameAsync(User.Identity.Name);
            var UserId = user.Id.ToString();

            if (cartItems.Count == 0)
            {
                ModelState.AddModelError("", "Empty Cart, please Add Product First");
            }

            if (ModelState.IsValid)
            {
                orderRepo.CreateOrder(order);
                cartRepo.ClearCart();

                return View("CheckOutComplete", order);
            }

            return View(order);
        }

        public IActionResult CheckOutComplete(Order order)
        {
            return View(order);
        }


        public IActionResult Payment(string id, string StripeEmail, string StripeToken)
        {
            var total = (long)decimal.Parse(id);
            var customers = new CustomerService();
            var charges = new ChargeService();
            var cutomer = customers.Create(new CustomerCreateOptions { Email = StripeEmail, Source = StripeToken });
            var charge = charges.Create(new ChargeCreateOptions
            {
                Customer = cutomer.Id,
                Amount = total*100,
                Currency = "usd"
            });
            if (charge.Status == "succeeded")
            {
                string BalanceTransactionId = charge.BalanceTransactionId;
                return RedirectToAction("Index", "Store");
            }
            else
            {
                return View();
            }

            return View("Store", "Index");
        }
    }
}

Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Amazon_Replica.Data;
using Amazon_Replica.Models;
using Amazon_Replica.Services;
using Microsoft.AspNetCore.Authorization;

namespace Amazon_Replica.Controllers
{
    [Authorize(Roles ="Admin,Moderator")]
    public class ProductsController : Controller
    {
        private readonly IProductRepo productRepo;
        private readonly ICategoryRepo categoryRepo;

        public ProductsController(IProductRepo context, ICategoryRepo context2)
        {
            productRepo = context;
            categoryRepo = context2;
        }

        // GET: Products
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = productRepo.GetAll();
            return View(applicationDbContext);
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || productRepo.GetAll() == null)
            {
                return NotFound();
            }

            var product = productRepo.GetDetails(id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(categoryRepo.GetAll(), "Id", "Name");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,Price,NumInStock,Image,CategoryId")] [FromForm]Product product)
        { 
            if (ModelState.IsValid)
            {
                Product newProduct = new Product()
                {
                    Name = product.Name,
                    Description = product.Description,
                    Price = product.Price,
                    CategoryId = product.CategoryId,
                    NumInStock = product.NumInStock,
                };
                if (Request.Form.Files.FirstOrDefault() != null)
                {
                    IFormFile file = Request.Form.Files.FirstOrDefault();
                    using (var stream = new MemoryStream())
                    {
                        await file.CopyToAsync(stream);
                        newProduct.Image = stream.ToArray();
                    }
                }
                productRepo.Insert(newProduct);
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(categoryRepo.GetAll(), "Id", "Name", product.CategoryId);
            return View(product);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || productRepo.GetAll() == null)
            {
                return NotFound();
            }

            var product = productRepo.GetDetails(id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(categoryRepo.GetAll(), "Id", "Name", product.CategoryId);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Price,NumInStock,Image,CategoryId")] [FromForm]Product product)
        {
            if (id != product.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if (Request.Form.Files.FirstOrDefault() != null)
                {
                    IFormFile file = Request.Form.Files.FirstOrDefault();
                    using (var stream = new MemoryStream())
                    {
                        await file.CopyToAsync(stream);
                        product.Image = stream.ToArray();
                    }
                }
                try
                {
                    productRepo.UpdateProduct(id,product);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(categoryRepo.GetAll(), "Id", "Name", product.CategoryId);
            return View(product);
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || productRepo.GetAll() == null)
            {
                return NotFound();
            }

            var product = productRepo.GetDetails(id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (productRepo.GetAll() == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Products'  is null.");
            }
            var product = productRepo.GetDetails(id);
            if (product != null)
            {
                productRepo.DeleteProduct(id);
            }

            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
          return (productRepo.GetAll()?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/UserRolesController.cs
using Amazon_Replica.Areas.Identity.Data;
using Amazon_Replica.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Amazon_Replica.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserRolesController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        public UserRolesController(UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
            var users = await _userManager.Users.ToListAsync();
            var userRolesViewModel = new List<UserRolesViewModel>();
            foreach (ApplicationUser user in users)
            {
                var thisViewModel = new UserRolesViewModel();
                thisViewModel.UserId = user.Id;
                thisViewModel.Email = user.Email;
                thisViewModel.FirstName = user.FirstName;
                thisViewModel.LastName = user.LastName;
                thisViewModel.Roles = await GetUserRoles(user);
                userRolesViewModel.Add(thisViewModel);
            }
            return View(userRolesViewModel);
        }

        public async Task<IActionResult> Manage(string userId)
        {
            ViewBag.userId = userId;
            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {userId} cannot be found";
                return View("NotFound");
            }
            ViewBag.UserName = user.UserName;
            var model = new List<ManageUserRolesViewModel>();
            foreach (var role in _roleManager.Roles)
            {
                var userRolesViewModel = new ManageUserRolesViewModel
                {
                    RoleId = role.Id,
                    RoleName = role.Name
                };
                if (await _userManager.IsInRoleAsync(user, role.Name))
                {
                    userRolesViewModel.Selected = true;
                }
                else
                {
                    userRolesViewModel.Selected = false;
                }
                model.Add(userRolesViewModel);
            }
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Manage(List<ManageUserRolesViewModel> model, string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                return View();
            }
            var roles = await _userManager.GetRolesAsync(user);
            var result = await _userManager.RemoveFromRolesAsync(user, roles);
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot remove user existing roles");
                return View(model);
            }
            result = await _userManager.AddToRolesAsync(user, model.Where(x => x.Selected).Select(y => y.RoleName));
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot add selected roles to user");
                return View(model);
            }
            return RedirectToAction("Index");
        }

        private async Task<List<string>> GetUserRoles(ApplicationUser user)
        {
            return new List<string>(await _userManager.GetRolesAsync(user));
        }
    }
}

Views/Shared/_AdminLayout.cshtml
@{
    Layout = "/Views/Shared/_Layout.cshtml";
}

<h1>Manage your web application</h1>

<div>
    <h2>Control Roles</h2>
    <hr />
    <div class="row">
        <div class="col-md-3">
            <partial name="_RolesNav" />
        </div>
        <div class="col-md-9">
            @RenderBody()
        </div>
    </div>
</div>

@section Scripts {
    @RenderSection("Scripts", required: false)
}

Views/Shared/_Layout.cshtml
@inject Amazon_Replica.Services.ICartRepo cart
@inject Amazon_Replica.Services.ICategoryRepo category
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Amazon MVC Project</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="~/lib/fontawesome/css/all.css" rel="stylesheet" />

    <!-- Libraries Stylesheet -->
    <link href="~/lib/animate/animate.min.css" rel="stylesheet">
    <link href="~/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/css/style.css" rel="stylesheet">
    <link href="~/css/MyCss.css" rel="stylesheet">
</head>

<body>
    <!-- Topbar Start -->
    <div class="container-fluid">
    <div class="row align-items-center bg-light py-3 px-xl-5 d-none d-lg-flex">
    <div class="col-lg-4">
    <a asp-controller="store" asp-action="Index" class="text-decoration-none">
    <span class="h1 text-uppercase text-primary bg-dark px-2">Ama</span>
    <span class="h1 text-uppercase text-dark bg-primary px-2 ml-n1">zon</span>
    </a>
    </div>
    <div class="col-lg-4 col-6 text-left">
                <form asp-action="GetByName" asp-controller="Store" asp-area="">
                    <div class="input-group">
                        <input type="text" name="name" class="form-control" placeholder="Search for products">
                        <div class="input-group-append">
                            <span class="input-group-text bg-transparent text-warning">
                                <i class="fa fa-search"></i>
                            </span>
                        </div>
                    </div>
                </form>
            </div>
    <div class="col-lg-4 col-6 text-right">
    <p class="m-0">Customer Service</p>
    <h5 class="m-0">+012 222 99463</h5>
    </div>
    </div>
    </div>
    <!-- Topbar End -->
    <!-- Navbar Start -->
    <div class="container-fluid bg-dark mb-30">
        <div class="row px-xl-5">
            <div class="col-lg-3 d-none d-lg-block">
                <a class="btn d-flex align-items-center justify-content-between bg-primary w-100" data-toggle="collapse" href="#navbar-vertical" style="height: 65px; padding: 0 30px;">
                    <h6 class="text-dark m-0"><i class="fa fa-bars mr-2"></i>Categories</h6>
                    <i class="fa fa-angle-down text-dark"></i>
                </a>
                <nav class="collapse position-absolute navbar navbar-vertical navbar-light align-items-start p-0 bg-light" id="navbar-vertical" style="width: calc(100% - 30px); z-index: 999;">
                    <div class="navbar-nav w-100">
                        @foreach(var item in category.GetAll())
                        {
                            <a asp-action="GetByCategory" asp-controller="Store" asp-route-id="@item.Id" class="nav-item nav-link">@item.Name</a>
                        }
                    </div>
                </nav>
            </div>
            <div class="col-lg-9">
                <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-2 py-lg-0 px-0">
                    <a href="" class="text-decoration-none d-block d-lg-none">
                        <span class="h2 text-uppercase text-dark bg-light px-2">Ama</span>
                        <span class="h2 text-uppercase text-light bg-primary px-2 ml-n1">zon</span>
                    </a>
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                        <div class="navbar-nav mr-auto py-0">

                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="RoleManager" asp-action="Index">Roles</a>
                                </li>
                            }
                            @if (User.IsInRole("Admin") || User.IsInRole("Moderator"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Order" asp-action="Index">Orders</a>
                                </li>
                            }
                            <a class="nav-link nav-link" asp-controller="store" asp-action="Index">Home</a>
                               
                        </div>
                        @{int counter = 0;}
                        @foreach (var item in @cart.GetCartItems())
                        {
                            counter += item.Quantity;
                        }
                        <a class="btn px-0 d-flex align-items-center g-2" asp-controller="Cart" asp-action="Index">
                                <i class="fas fa-shopping-cart text-primary mr-1"></i>
                                <span class="badge text-secondary border border-secondary rounded-circle" style="padding-bottom: 2px;">@counter</span>
                        </a>

                        <partial name="_LoginPartial" />
                    </div>
                </nav>
            </div>
        </div>
    </div>
    <!-- Navbar End -->
    <!-- Carousel Start -->
    <!-- Carousel End -->
    <!-- Featured Start -->
    <!-- Featured End -->
    <!-- Categories Start -->
    <!-- Categories End -->
    <!-- Products Start -->
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                @RenderBody()
                @if (IsSectionDefined("Scripts"))
                {
                    RenderSection("Scripts");
                }
            </div>
        </div>
    </div>
    <!-- Products End -->
    <!-- Offer Start -->
    <!-- Offer End -->
    <!-- Products Start -->
    <!-- Products End -->
    <!-- Vendor Start -->
    <div class="container-fluid py-5">
        <div class="row px-xl-5">
            <div class="col">
                <div class="owl-carousel vendor-carousel">
                    <div class="bg-light p-4">
                        <img src="~/img/vendor-1.jpg" alt="">
                    </div>
                    <div class="bg-light p-4">
                        <img src="~/img/vendor-2.jpg" alt="">
                    </div>
                    <div class="bg-light p-4">
                        <img src="~/img/vendor-3.jpg" alt="">
                    </div>
                    <div class="bg-light p-4">
                        <img src="~/img/vendor-4.jpg" alt="">
                    </div>
                    <div class="bg-light p-4">
                        <img src="~/img/vendor-5.jpg" alt="">
                    </div>
                    <div class="bg-light p-4">
                        <img src="~/img/vendor-6.jpg" alt="">
                    </div>
                    <div class="bg-light p-4">
                        <img src="~/img/vendor-7.jpg" alt="">
                    </div>
                    <div class="bg-light p-4">
                        <img src="~/img/vendor-8.jpg" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Vendor End -->
    <!-- Footer Start -->
    <div class="container-fluid bg-dark text-secondary mt-5 pt-5">
        <div class="row px-xl-5 pt-5">
            <div class="col-lg-6 col-md-12 mb-5 pr-3 pr-xl-5">
                <h5 class="text-secondary text-uppercase mb-4">Get In Touch</h5>
                <p class="mb-4">No dolore ipsum accusam no lorem. Invidunt sed clita kasd clita et et dolor sed dolor. Rebum tempor no vero est magna amet no</p>
                <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>123 Street, New York, USA</p>
                <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@example.com</p>
                <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890</p>
            </div>
            <div class="col-lg-6 col-md-12">
                <h5 class="text-secondary text-uppercase mb-4">Newsletter</h5>
                <p>Duo stet tempor ipsum sit amet magna ipsum tempor est</p>
                <form action="">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Your Email Address">
                        <div class="input-group-append">
                            <button class="btn btn-primary">Sign Up</buthton>
                        </div>
                    </div>
                </form>
                <h6 class="text-secondary text-uppercase mt-4 mb-3">Follow Us</h6>
                <div class="d-flex">
                    <a class="btn btn-primary btn-square mr-2" href="#"><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-primary btn-square mr-2" href="#"><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-primary btn-square mr-2" href="#"><i class="fab fa-linkedin-in"></i></a>
                    <a class="btn btn-primary btn-square" href="#"><i class="fab fa-instagram"></i></a>
                </div>
            </div>
        </div>
        <div class="row border-top mx-xl-5 py-4" style="border-color: rgba(256, 256, 256, .1) !important;">
            <div class="col-md-6 px-xl-0">
                <p class="mb-md-0 text-center text-md-left text-secondary">
                    &copy; <a class="text-primary" href="#">Domain</a>. All Rights Reserved. Designed
                    by
                    <a class="text-primary" href="https://htmlcodex.com">HTML Codex</a>
                </p>
            </div>
            <div class="col-md-6 px-xl-0 text-center text-md-right">
                <img class="img-fluid" src="img/payments.png" alt="">
            </div>
        </div>
    </div>
    <!-- Footer End -->
    <!-- Back to Top -->
    <a href="#" class="btn btn-primary back-to-top"><i class="fa fa-angle-double-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/easing/easing.min.js"></script>
    <script src="~/lib/owlcarousel/owl.carousel.min.js"></script>

    <!-- Contact Javascript File -->
    <script src="~/mail/jqBootstrapValidation.min.js"></script>
    <script src="~/mail/contact.js"></script>

    <!-- Template Javascript -->
    <script src="~/js/main.js"></script>
</body>

</html>

Views/Shared/_Layout1.cshtml
@using Microsoft.AspNetCore.Identity
@using Amazon_Replica.Areas.Identity.Data
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Amazon_Replica</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Amazon_Replica.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/MyCss.css" asp-append-version="true" />
    <link href="~/lib/fontawesome/css/all.css" rel="stylesheet" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Amazon_Replica</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="RoleManager" asp-action="Index">Roles Manager</a>
                            </li>
                        }
                        @if (User.IsInRole("Admin") || User.IsInRole("Moderator"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products Manager</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Categories Manager</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Store" asp-action="Index">Store</a>
                        </li>
                    </ul>
                    <a class="nav-link text-dark float-right" asp-controller="Cart" asp-action="Index"><i class="fa-solid fa-cart-shopping"></i></a>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Amazon_Replica - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_RolesNav.cshtml
@using Amazon_Replica.Areas.Identity.Data;

<ul class="nav nav-pills flex-column">
    <li class="nav-item"><a class="nav-item nav-link active" id="roles" asp-area="" asp-controller="RoleManager" asp-action="Index">Roles</a></li>
    <br />
    <li class="nav-item"><a class="nav-item nav-link active" id="userRoles" asp-area="" asp-controller="UserRoles" asp-action="Index">UserRoles</a></li>
</ul>